// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE0khDo2BAeRk6lMkbBoUxQStAK_SpEmM',
    appId: '1:1010074873335:web:c7b7f70e34bb76284c12f2',
    messagingSenderId: '1010074873335',
    projectId: 'classic-parts-388f5',
    authDomain: 'classic-parts-388f5.firebaseapp.com',
    storageBucket: 'classic-parts-388f5.appspot.com',
    measurementId: 'G-4TNV0NYBEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdobIqFk3aNhHVVE1VjPPuCVEt6A6KleM',
    appId: '1:1010074873335:android:67080892138c2e2d4c12f2',
    messagingSenderId: '1010074873335',
    projectId: 'classic-parts-388f5',
    storageBucket: 'classic-parts-388f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQSCLeEAc9QNngzMHoXASBNYCJ0gUKIGM',
    appId: '1:1010074873335:ios:e40f9bea477213db4c12f2',
    messagingSenderId: '1010074873335',
    projectId: 'classic-parts-388f5',
    storageBucket: 'classic-parts-388f5.appspot.com',
    iosBundleId: 'com.classic.classicparts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQSCLeEAc9QNngzMHoXASBNYCJ0gUKIGM',
    appId: '1:1010074873335:ios:aa8d5f2411c3f1274c12f2',
    messagingSenderId: '1010074873335',
    projectId: 'classic-parts-388f5',
    storageBucket: 'classic-parts-388f5.appspot.com',
    iosBundleId: 'com.classic.classicparts.RunnerTests',
  );
}
